export const AUTH_REGISTER_USER = "AUTH_REGISTER_USER";
export const AUTH_LOGIN_USER = "AUTH_LOGIN_USER";
export const AUTH_RESET_PASSWORD = "AUTH_RESET_PASSWORD";
export const AUTH_LOGOUT_USER = "AUTH_LOGOUT_USER";

export const SETTINGS_UPDATE_NAME = "SETTINGS_UPDATE_NAME";
export const SETTINGS_UPDATE_EMAIL = "SETTINGS_UPDATE_EMAIL";
export const SETTINGS_UPDATE_PASSWORD = "SETTINGS_UPDATE_PASSWORD";

export const USERS_GET_DATA = "USERS_GET_DATA";
