export const AUTH_REGISTER_USER = "AUTH_REGISTER_USER";
export const AUTH_LOGIN_USER = "AUTH_LOGIN_USER";
export const AUTH_RESET_PASSWORD = "AUTH_RESET_PASSWORD";
export const AUTH_LOGOUT_USER = "AUTH_LOGOUT_USER";

export const SETTINGS_UPDATE_NAME = "SETTINGS_UPDATE_NAME";
export const SETTINGS_UPDATE_EMAIL = "SETTINGS_UPDATE_EMAIL";
export const SETTINGS_UPDATE_PASSWORD = "SETTINGS_UPDATE_PASSWORD";

export const USERS_GET_DATA = "USERS_GET_DATA";

export const NOTES_ADD_NOTE = "NOTES_ADD_NOTE";
export const NOTES_UPDATE_NOTE = "NOTES_UPDATE_NOTE";
export const NOTES_DELETE_NOTE = "NOTES_DELETE_NOTE";
export const NOTES_CHECKED_NOTE = "NOTES_CHECKED_NOTE";
export const NOTES_CLEAR_NOTES = "NOTES_CLEAR_NOTES";
export const NOTES_CLEAR_NOTES_FOR_DAY = "NOTES_CLEAR_NOTES_FOR_DAY";
export const NOTES_SET_NOTES = "NOTES_SET_NOTES";
export const NOTES_CLEAR_ALL_NOTES = "NOTES_CLEAR_ALL_NOTES";
